Hotbar autoset
MortenTobiasNielsen/TAS-Helper-for-Factorio pull request #35
Opened 2022-09-05 10:45 UTC by theis999

Added the option to autoset the hotbar (quickbar)

- Added mod setting file, where the user can configure their hotbar items
- Added folder "locale/en"
- Added locale file to convert hotbar settings to human text
- Added split_string lua function
- Added set_quick_bar lua function to handle the conversion between settings -> hotbar
- Added event on_cutscene_cancelled that runs the set_quick_bar function

Upgraded to cpp17 to create directories "locale" and "locale/en"
Suppressed a warning due codecvt_utf8 being deprecated

I also added a few default hotbar sets, it is not an exhaustive list, just a start.

2022-09-05 11:00 UTC, theis999 commented
Related to #20

2022-09-05 18:12 UTC, MortenTobiasNielsen requested changes
A few minor changes. This is a very nice feature and well worked out - thanks. 👍

2022-09-05 18:12 UTC, MortenTobiasNielsen commented on control_info.h
> +local settings_short = "DunRaider-quickbar-"
You are very welcome to take credit for this - it is your contribution. :)

2022-09-05 18:12 UTC, MortenTobiasNielsen commented on control_info.h
> +	"burner-mining-drill","stone-furnace","electric-mining-drill","assembling-machine-1","lab","boiler","steam-engine","offshore-pump","pipe","pipe-to-ground"),
I might make some changes to this at some point. I think that some of these (e.g. rail-signal, rail-chain-signal, train-stop) will never or very rarely be used in a TAS.

2022-09-05 18:12 UTC, MortenTobiasNielsen commented on EZRaiderz-TAS-Helper.vcxproj
> +      <LanguageStandard>stdcpp17</LanguageStandard>
Take it to stdcpp20 if it doesn't give problems. :)

2022-09-05 18:33 UTC, MortenTobiasNielsen commented
closes #20

2022-09-05 21:44 UTC, theis999 commented on cMain.cpp
> +		fs::create_directory(generate_code_folder_location + "\\locale\\en");
You are nearly correct. It does have to be 2 seperate **create_directory** calls. It appears like i was overly cautious, since i can't provoke errors that should have been caught by **is_directory** and **exists**, so i will remove them.

2022-09-05 21:45 UTC, theis999 commented on control_info.h
> +local settings_short = "DunRaider-quickbar-"
Thank you, but it is fine 👌

2022-09-05 21:51 UTC, theis999 commented on control_info.h
> +	"burner-mining-drill","stone-furnace","electric-mining-drill","assembling-machine-1","lab","boiler","steam-engine","offshore-pump","pipe","pipe-to-ground"),
Figuring out what a user might want, honestly seemed much harder than making the code to support it 😎
and i am sure there was supposed to be a small-electric-pole in there somewhere

2022-09-05 21:52 UTC, theis999 commented on EZRaiderz-TAS-Helper.vcxproj
> +      <LanguageStandard>stdcpp17</LanguageStandard>
Fair, i'll give it go.

2022-09-05 22:13 UTC, theis999 commented on EZRaiderz-TAS-Helper.vcxproj
> +      <LanguageStandard>stdcpp17</LanguageStandard>
It appears to be fine.

2022-09-05 22:27 UTC, theis999 commented
Rebased and updated.

2022-09-06 05:36 UTC, MortenTobiasNielsen commented on cMain.cpp
> +		fs::create_directory(generate_code_folder_location + "\\locale\\en");
Why isn't it possible to use "std::filesystem::create_directories(generate_code_folder_location + "\\locale\\en");" it worked for me? Are there some edge case?

2022-09-06 13:47 UTC, theis999 commented on cMain.cpp
> +		fs::create_directory(generate_code_folder_location + "\\locale\\en");
Oh i misread you. I didn't see that it was in plural, that could work.

2022-09-06 13:52 UTC, theis999 commented on cMain.cpp
> +		fs::create_directory(generate_code_folder_location + "\\locale\\en");
It worked, thanks.

2022-09-06 16:01 UTC, MortenTobiasNielsen approved these changes

2022-09-06 16:01 UTC, merged