Changed control_info to add sounds when placing tiles.
MortenTobiasNielsen/TAS-Helper-for-Factorio pull request #38
Opened 2022-09-05 19:55 UTC by MortenTobiasNielsen

closes #25 

Sets run = true as the default, so the steps executes until release is written in the console.

2022-09-05 19:55 UTC, MortenTobiasNielsen commented
@theis999 please review this PR

2022-09-05 21:13 UTC, theis999 requested changes
You over complicated it a bit

2022-09-05 21:13 UTC, theis999 commented on control_info.h
> +local run = true
👍

2022-09-05 21:13 UTC, theis999 commented on control_info.h
> +			-- something can be done here with item:gsub, but I couldn't get it to work - kebt getting refined-d-concrete when using item:gsub("hazard-", "")
It looks to me like [there is effectively 2 place tile sounds](https://github.com/wube/factorio-data/blob/master/base/prototypes/tile/tiles.lua). Landfill and "concrete", where concrete is all the concrete types and stone path. Which also lines up with sound files are actually played, which you can see through _f4->show-recently-played-sound-info_.

2022-09-06 05:48 UTC, MortenTobiasNielsen commented on control_info.h
> +			-- something can be done here with item:gsub, but I couldn't get it to work - kebt getting refined-d-concrete when using item:gsub("hazard-", "")
It also felt overly complicated. :) So I should pretty much play stone-path unless the item is landfill?

2022-09-06 07:38 UTC, theis999 commented on control_info.h
> +			-- something can be done here with item:gsub, but I couldn't get it to work - kebt getting refined-d-concrete when using item:gsub("hazard-", "")
That appears to be what the base game does, so yes.

2022-09-06 17:42 UTC, theis999 approved these changes
Looks perfect

2022-09-06 17:56 UTC, MortenTobiasNielsen commented
It unfortunately doesn't work as intended. There is no check whether the players should actually be able to place tiles at the position specified.

2022-09-06 18:27 UTC, theis999 commented
I see, are you working on it right now? or would you rather have me take a look at it.

2022-09-06 18:31 UTC, MortenTobiasNielsen commented
It would be nice if you would take a look at it - I don't have more time today.

2022-09-07 18:51 UTC, MortenTobiasNielsen commented
@theis999 I think I have fixed it now and it also works with hazard variation.

2022-09-08 21:25 UTC, theis999 approved these changes
Good job. If you merge two hazard types then i approve.

2022-09-08 21:25 UTC, theis999 commented on control_info.h
> +	return dis <= 10.25 -- It seems like 10.25 aligns best with the current walking algorithm
Good use of comment to explain a magic number

2022-09-08 21:25 UTC, theis999 commented on control_info.h
> +					player.surface.set_tiles({{position = target_position, name = item.."-left"}})
It would be more correct to use building direction to set hazard direction.

2022-09-08 21:25 UTC, theis999 commented on control_info.h
> +				elseif (item == "refined-hazard-concrete") then
It is possible to combine refined-hazard and hazard.

2022-09-08 21:25 UTC, theis999 commented on control_info.h
> +					player.surface.set_tiles({{position = target_position, name = item.."-left"}})
but on the other hand, i don't think hazard concrete will ever be used in a tas

2022-09-09 05:16 UTC, MortenTobiasNielsen commented on control_info.h
> +					player.surface.set_tiles({{position = target_position, name = item.."-left"}})
I did a little testing, but couldn't really see that hazard had a direction. It seems like it turns the same way and it would be difficult to use building direction, given that it has four (north, south, east, and west), but hazard only have left and right. 

I think you are right, in a TAS it (or any speed run for that matter) it would be a waste of time to use hazard.

2022-09-09 05:20 UTC, MortenTobiasNielsen commented on control_info.h
> +				elseif (item == "refined-hazard-concrete") then
Good addition - I have changed it.

2022-09-09 06:19 UTC, theis999 approved these changes

2022-09-09 08:59 UTC, merged