Fixed a few issues
MortenTobiasNielsen/TAS-Helper-for-Factorio pull request #39
Opened 2022-09-06 18:27 UTC by MortenTobiasNielsen

2022-09-06 18:27 UTC, MortenTobiasNielsen commented
@theis999

2022-09-07 09:33 UTC, theis999 requested changes
I typically like to separate different issues into different commits. This has the dual purpose of having more concise commit messages and more specific git logs per file/line.
Here i have to read the git branch to even understand what is going on.

I would rather see you separate this into 2 commits:
1. To fix build issues
2. To fix rotate bug

The actual changes seem fine.

1.

2022-09-07 09:33 UTC, theis999 commented on EZRaiderz-TAS-Helper.vcxproj
> +    <PlatformToolset>v143</PlatformToolset>
I see you upgraded to vs2022

2022-09-07 09:33 UTC, theis999 commented on cMain.cpp
> +	if (units < 1 && (rbtn_rotate->GetValue() || rbtn_idle->GetValue())) {
It is always interesting when magic-values change. But if you think it is an improvement, then it is fine.

2022-09-07 09:33 UTC, theis999 commented on control_info.h
> +std::string control_lua2 = R"control_lua2(
👌

2022-09-07 10:08 UTC, MortenTobiasNielsen commented on cMain.cpp
> +	if (units < 1 && (rbtn_rotate->GetValue() || rbtn_idle->GetValue())) {
The application would try to rotate buildings "All" amount of times, if the units wasn't specified, which would break the application, I do though agree that magic variables isn't a good thing to have. :)

2022-09-07 10:09 UTC, MortenTobiasNielsen commented on EZRaiderz-TAS-Helper.vcxproj
> +    <PlatformToolset>v143</PlatformToolset>
Yeah I thought it would make sense to do - vs2022 are relatively mature now.

2022-09-07 16:46 UTC, merged