Added auto-put functionality
MortenTobiasNielsen/TAS-Helper-for-Factorio pull request #45
Opened 2022-09-09 17:24 UTC by MortenTobiasNielsen

Made some restructuring to remove hard-coded strings

2022-09-09 22:55 UTC, theis999 requested changes
I believe the logic in line 926 is wrong.

I have pointed out a few things that could maybe be done better, but since they were just updated and not made this way in this commit, it is fine to leave it for now.

2022-09-09 22:55 UTC, theis999 commented on cMain.cpp
> +				update_tasks_grid();
You are removing the same line your adding?

2022-09-09 22:55 UTC, theis999 commented on cMain.cpp
> +					if (check_furnace->IsChecked() && to_check == struct_auto_put_furnace_list.stone || to_check == struct_auto_put_furnace_list.steel) {
Why specifically stone and steel? and not copper and iron

2022-09-09 22:55 UTC, theis999 commented on cMain.cpp
> +					if (check_burner->IsChecked() && to_check == struct_auto_put_burner_list.burner_mining_drill || to_check == struct_auto_put_burner_list.burner_inserter || to_check == struct_auto_put_burner_list
If i remember correctly, && is done before ||. So you may need a parentese to achieve the logic you want.

2022-09-09 22:55 UTC, theis999 commented on cMain.cpp
> +						auto_put(recipe[i], recipe[i + 1], struct_from_into_list.input);
This took me a few minutes to comprehend 😎

2022-09-09 22:55 UTC, theis999 commented on cMain.cpp
> +	if (task == struct_tasks_list.start) {
With this many if statements on the same variable, we should consider a switch instead.

2022-09-09 22:55 UTC, theis999 commented on utils.h
> +																		 { "Utility science pack", {"Flying robot frame", "1", "Low density structure", "3", "Processing unit", "2" }},
How do you have the patience to type all of this in?

2022-09-09 22:55 UTC, theis999 commented on utils.h
> +} struct_science_list;
Using structs to list constants seems wrong to me. I couldn't find any other way on google, so i guess it is how it is done. I want the enums from c# 😒

2022-09-09 22:57 UTC, theis999 approved these changes

2022-09-09 22:57 UTC, theis999 approved these changes

2022-09-09 23:05 UTC, theis999 requested changes
It feels like i have read this code before  😒 
Anyway using an if statement to set a bool is obviously suspect

2022-09-10 06:49 UTC, MortenTobiasNielsen reviewed
Answering comments

2022-09-10 06:49 UTC, MortenTobiasNielsen commented on cMain.cpp
> +					if (check_furnace->IsChecked() && to_check == struct_auto_put_furnace_list.stone || to_check == struct_auto_put_furnace_list.steel) {
This is to check if the building being build is a stone/steel furnace and then creating a put coal task if that is the case. It is not to put stone/steel/copper/iron into a furnace or set a recipe for it. :)

2022-09-10 06:49 UTC, MortenTobiasNielsen commented on cMain.cpp
> +				update_tasks_grid();
No clue why github thinks I changed anything here.

2022-09-10 06:49 UTC, MortenTobiasNielsen commented on cMain.cpp
> +					if (check_burner->IsChecked() && to_check == struct_auto_put_burner_list.burner_mining_drill || to_check == struct_auto_put_burner_list.burner_inserter || to_check == struct_auto_put_burner_list
I have tested the logic with all three and it works. It should go "is it a burner?" and then check each of the "or" statements afterwards.

2022-09-10 06:49 UTC, MortenTobiasNielsen commented on cMain.cpp
> +						auto_put(recipe[i], recipe[i + 1], struct_from_into_list.input);
Understandable it took me a good amount more than a minute to figure out. :D 

It might have helped a little if I had renamed my "testing" object. :)

2022-09-10 06:49 UTC, MortenTobiasNielsen commented on cMain.cpp
> +	if (task == struct_tasks_list.start) {
I am not too familiar with the switch statement in C++, it seems like it only works with enums, which is also behaving a bit strangely in C++ compared to C#. I might do some refactoring at some point where I explore enums and switch statements and change all the large if clusters to switch statements.

2022-09-10 06:49 UTC, MortenTobiasNielsen commented on utils.h
> +																		 { "Utility science pack", {"Flying robot frame", "1", "Low density structure", "3", "Processing unit", "2" }},
Well I started with the once I knew I would need to a short run (steel axe, GOTLAP). That turned out to not be as painful as I would have imagined, so I took a little more and in the end ended up with most of it. :)

2022-09-10 06:49 UTC, MortenTobiasNielsen commented on utils.h
> +} struct_science_list;
Yeah it is sort of strange to do it like this and I would also like the enums from C#. I do though also need the actual text string name of these most places, so I would have to do some kind of "ToString" all over the place and I am not sure how enums behave in C++.

2022-09-10 06:53 UTC, MortenTobiasNielsen commented on cMain.cpp
> +					if (check_furnace->IsChecked() && to_check == struct_auto_put_furnace_list.stone || to_check == struct_auto_put_furnace_list.steel) {
This is to check that the building being build is a stone/steel furnace and make a put coal task if that is the case. It is not to put stone/steel/copper/iron into a furnace. :)

2022-09-10 06:53 UTC, MortenTobiasNielsen commented on cMain.cpp
> +							check_furnace->SetValue(false);
That is so much cleaner - thanks.

2022-09-10 07:25 UTC, MortenTobiasNielsen commented on cMain.cpp
> +	if (task == struct_tasks_list.start) {
I have made an issue to "Refactor away from if clusters"

2022-09-10 07:25 UTC, MortenTobiasNielsen commented on utils.h
> +} struct_science_list;
I have made an issue to "Refactor and use utils.h objects".

2022-09-10 08:58 UTC, theis999 commented on cMain.cpp
> +					if (check_furnace->IsChecked() && to_check == struct_auto_put_furnace_list.stone || to_check == struct_auto_put_furnace_list.steel) {
Oh i see, that makes sense.

2022-09-10 09:02 UTC, theis999 commented on cMain.cpp
> +					if (check_burner->IsChecked() && to_check == struct_auto_put_burner_list.burner_mining_drill || to_check == struct_auto_put_burner_list.burner_inserter || to_check == struct_auto_put_burner_list
If it works, then it is alright.

2022-09-10 09:09 UTC, theis999 commented on utils.h
> +																		 { "Utility science pack", {"Flying robot frame", "1", "Low density structure", "3", "Processing unit", "2" }},
A reasonable approach 😉

2022-09-10 09:16 UTC, theis999 commented on utils.h
> +} struct_science_list;
One alternative to structs, is to use namespaces

`namespace science_packs{
 std::string red = "automation-science-pack", green = "logistic-science-pack"
}`

2022-09-10 09:23 UTC, theis999 approved these changes

2022-09-10 09:58 UTC, MortenTobiasNielsen commented on utils.h
> +} struct_science_list;
I see I will have that in mind if I am the one taking the refactor task.

2022-09-10 09:58 UTC, merged