Convert lua strings to files
MortenTobiasNielsen/TAS-Helper-for-Factorio pull request #53
Opened 2022-09-10 15:42 UTC by theis999

### Just for show

Lua code is moved to separate files. Those files are set to output on build.

### File settings
The files will be moved from the TAS-helper to the TAS mod on script generation. Script files that up to date is skipped, except the goal file and the step file.
The goal file changes based on which goal you choose, but the copy_from file remains unchanged which is why it needs to be updated.

### Lua setup
The goals are split into separate files. 
control.lua now require a goal.lua file
control1 and control2 is merged together

2022-09-13 16:07 UTC, MortenTobiasNielsen commented
Is this up to date with the master branch?

2022-09-13 17:35 UTC, theis999 commented
It was as of 2 hours ago

2022-09-14 09:53 UTC, MortenTobiasNielsen requested changes

2022-09-14 09:53 UTC, MortenTobiasNielsen commented on info.json
> +	"version": "0.0.2",
This should be version 0.0.5

2022-09-14 09:54 UTC, MortenTobiasNielsen commented
control_info.h should be cleaned or deleted.

2022-09-14 10:14 UTC, theis999 commented on info.json
> +	"version": "0.0.2",
Correct. Looking at it, info.json can't be made this way. Since we need to change the mod name.

2022-09-14 10:17 UTC, MortenTobiasNielsen commented on info.json
> +	"version": "0.0.2",
Ohh yeah you are right. Info might live best in c++. :)

2022-09-14 10:42 UTC, theis999 commented on info.json
> +	"version": "0.0.2",
Agreed, i reverted to the old way.

2022-09-14 10:50 UTC, theis999 commented
I have reverted to the old info.json and cleaned the control_info.h

2022-09-14 13:13 UTC, merged